# Generated by Django 5.1.4 on 2026-04-23 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='owner_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('display_name', models.CharField(blank=True, default='', help_text='Public display name (e.g. brand). Falls back to user name if empty.', max_length=200)),
                ('company_legal_name', models.CharField(blank=True, default='', max_length=255)),
                ('trade_license_number', models.CharField(blank=True, default='', max_length=100)),
                ('license_expiry', models.DateField(blank=True, null=True)),
                ('website', models.URLField(blank=True, default='')),
                ('logo', models.ImageField(blank=True, default='', upload_to='owner_logos/%Y/%m/')),
                ('verified_badge', models.BooleanField(default=False, help_text='KYC / business verification badge (set by staff after review).')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('public_slug', models.SlugField(blank=True, help_text='Optional /company/{slug} public page.', max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='owner_type',
            field=models.CharField(blank=True, choices=[('INDIVIDUAL', 'Individual'), ('AGENT', 'Agent / broker'), ('COMPANY', 'Real estate company')], default='', help_text='Set for landlords: individual, agent, or company.', max_length=10),
        ),
    ]
