# Generated by Django 5.1

from django.db import migrations, models


def forward_set_landlord_flags(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    for u in User.objects.filter(role="LANDLORD").iterator():
        u.landlord_eligible = True
        u.active_app_mode = "LANDLORD"
        u.save(update_fields=["landlord_eligible", "active_app_mode"])


def backward_noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_listing_packages"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="landlord_eligible",
            field=models.BooleanField(
                default=False,
                help_text="True if the user may list properties: registered as landlord or completed owner opt-in.",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="active_app_mode",
            field=models.CharField(
                choices=[("RENTER", "Renter / browsing"), ("LANDLORD", "Property owner / listings")],
                db_index=True,
                default="RENTER",
                help_text="Last selected dashboard: renter vs property owner (same login).",
                max_length=10,
            ),
        ),
        migrations.RunPython(forward_set_landlord_flags, backward_noop),
    ]
