# Generated by Django 5.1 on 2026-05-07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_user_landlord_eligible_and_app_mode"),
    ]

    operations = [
        migrations.CreateModel(
            name="IdentityVerificationSubmission",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[("PENDING", "Pending"), ("APPROVED", "Approved"), ("REJECTED", "Rejected")],
                        db_index=True,
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("id_document_front", models.ImageField(blank=True, default="", upload_to="verification/id_front/%Y/%m/")),
                ("id_document_back", models.ImageField(blank=True, default="", upload_to="verification/id_back/%Y/%m/")),
                ("selfie", models.ImageField(blank=True, default="", upload_to="verification/selfie/%Y/%m/")),
                ("review_notes", models.TextField(blank=True, default="")),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="identity_verifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="identityverificationsubmission",
            index=models.Index(fields=["user", "status"], name="accounts_id_user_id_7e3350_idx"),
        ),
    ]

