# Generated by Django 5.1.4 on 2026-05-07 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_identity_verification_submission'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='identityverificationsubmission',
            new_name='accounts_id_user_id_3af0b0_idx',
            old_name='accounts_id_user_id_7e3350_idx',
        ),
        migrations.AlterField(
            model_name='user',
            name='landlord_eligible',
            field=models.BooleanField(default=False, help_text='True if the user may list properties: registered as a property owner or completed owner opt-in.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='owner_type',
            field=models.CharField(blank=True, choices=[('INDIVIDUAL', 'Individual'), ('AGENT', 'Agent / broker'), ('COMPANY', 'Real estate company')], default='', help_text='Set for property owners: individual, agent, or company.', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('RENTER', 'Renter'), ('LANDLORD', 'Property Owner'), ('ADMIN', 'Admin')], default='RENTER', max_length=10),
        ),
    ]
