# Generated by Django 5.1.4 on 2026-05-08 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_accounts_id_user_id_7e3350_idx_accounts_id_user_id_3af0b0_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.JSONField(blank=True, default=list, help_text="Multi-role membership, e.g. ['RENTER','LANDLORD']. Backward-compatible with role/landlord_eligible."),
        ),
    ]
