# Generated by Django 5.1.4 on 2026-04-19 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='contact_agreement_ack',
            field=models.BooleanField(default=False, help_text='Renter confirmed they agreed this visit via chat or phone in advance.'),
        ),
        migrations.AddField(
            model_name='booking',
            name='visit_reminder_sent',
            field=models.BooleanField(db_index=True, default=False, help_text='Set when a visit-day reminder notification was sent.'),
        ),
    ]
