# Generated by Django 5.1.4 on 2026-04-19 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('NEW_LISTING', 'New Listing'), ('PRICE_DROP', 'Price Drop'), ('BOOKING_CONFIRMED', 'Booking Confirmed'), ('BOOKING_CANCELLED', 'Booking Cancelled'), ('NEW_MESSAGE', 'New Message'), ('REVIEW_RECEIVED', 'Review Received'), ('LISTING_VERIFIED', 'Listing Verified'), ('PAYMENT_RECEIVED', 'Payment Received'), ('BOOKING_VISIT_REQUEST', 'Visit Booking Request'), ('VISIT_REMINDER', 'Visit Reminder'), ('SYSTEM', 'System')], db_index=True, max_length=32),
        ),
    ]
