# Generated by Django 5.1.4 on 2026-04-23 19:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_visit_contact_and_notification_types'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, default='', help_text="Short name shown in the app (e.g. 'Near Bole').", max_length=100)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('sub_city', models.CharField(blank=True, default='', help_text='If empty, the whole city is watched (text match).', max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Optional center for radius matching when the listing has coordinates.', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('radius_km', models.PositiveSmallIntegerField(default=5, help_text='Used when you set lat/lng; listing must be within this distance (km) if it has coordinates.')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='notificatio_user_id_34d70c_idx')],
            },
        ),
    ]
