# Generated by Django 5.1.4 on 2026-05-07 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_location_alerts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('NEW_LISTING', 'New Listing'), ('PRICE_DROP', 'Price Drop'), ('BOOKING_CONFIRMED', 'Booking Confirmed'), ('BOOKING_CANCELLED', 'Booking Cancelled'), ('NEW_MESSAGE', 'New Message'), ('REVIEW_RECEIVED', 'Review Received'), ('LISTING_VERIFIED', 'Listing Verified'), ('PAYMENT_RECEIVED', 'Payment Received'), ('BOOKING_VISIT_REQUEST', 'Visit Booking Request'), ('VISIT_REMINDER', 'Visit Reminder'), ('SYSTEM', 'System'), ('LISTING_PACKAGE_LOW', 'Listing package: few credits left'), ('LISTING_PACKAGE_DEPLETED', 'Listing package: credits used up'), ('LISTING_PACKAGE_EXPIRING', 'Listing package: expiring soon')], db_index=True, max_length=32),
        ),
    ]
