# Generated by GPT-5.2 on 2026-05-12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0004_alter_notification_notification_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="locationalert",
            name="property_type",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optional filter, matches Property.property_type (e.g. APARTMENT). Leave blank for any.",
                max_length=20,
            ),
        ),
    ]

