# Generated by Django 5.1.4 on 2026-04-01 07:55

import django.core.validators
import django.db.models.deletion
import properties.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water_availability', models.CharField(choices=[('ALWAYS', 'Always Available'), ('SOMETIMES', 'Sometimes Available'), ('RARELY', 'Rarely Available')], default='SOMETIMES', max_length=10)),
                ('electricity_stability', models.CharField(choices=[('STABLE', 'Stable'), ('MODERATE', 'Moderate'), ('UNSTABLE', 'Unstable')], default='MODERATE', max_length=10)),
                ('has_parking', models.BooleanField(default=False)),
                ('has_wifi', models.BooleanField(default=False)),
                ('has_security', models.BooleanField(default=False)),
                ('has_generator', models.BooleanField(default=False)),
                ('is_furnished', models.BooleanField(default=False)),
                ('has_elevator', models.BooleanField(default=False)),
                ('has_balcony', models.BooleanField(default=False)),
                ('has_garden', models.BooleanField(default=False)),
                ('has_cctv', models.BooleanField(default=False)),
                ('pets_allowed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'amenities',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('sub_city', models.CharField(db_index=True, max_length=100)),
                ('woreda', models.CharField(blank=True, default='', max_length=50)),
                ('kebele', models.CharField(blank=True, default='', max_length=50)),
                ('specific_location', models.CharField(help_text='Landmark description, e.g. "near Bole Medhanialem"', max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-90)])),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-180)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['city', 'sub_city'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('description', models.TextField()),
                ('property_type', models.CharField(choices=[('APARTMENT', 'Apartment'), ('VILLA', 'Villa'), ('CONDOMINIUM', 'Condominium'), ('SERVICE_HOUSE', 'Service House'), ('REAL_ESTATE', 'Real Estate'), ('HALL_RENTAL', 'Hall Rental')], db_index=True, max_length=15)),
                ('bedrooms', models.CharField(blank=True, choices=[('STUDIO', 'Studio'), ('ONE', '1 Bedroom'), ('TWO', '2 Bedrooms'), ('THREE_PLUS', '3+ Bedrooms')], default='', max_length=10)),
                ('bathrooms', models.PositiveIntegerField(default=1)),
                ('area_sqm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_monthly', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('price_currency', models.CharField(default='ETB', max_length=3)),
                ('is_verified', models.BooleanField(db_index=True, default=False)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('is_available', models.BooleanField(db_index=True, default=True)),
                ('verification_date', models.DateTimeField(blank=True, null=True)),
                ('total_views', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amenities', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='property', to='properties.amenities')),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='property', to='properties.location')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'properties',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HallDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.PositiveIntegerField(help_text='Maximum number of guests')),
                ('price_per_hour', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_per_day', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('has_sound_system', models.BooleanField(default=False)),
                ('has_stage', models.BooleanField(default=False)),
                ('decoration_allowed', models.BooleanField(default=True)),
                ('catering_available', models.BooleanField(default=False)),
                ('is_indoor', models.BooleanField(default=True)),
                ('hall_type', models.CharField(blank=True, choices=[('WEDDING', 'Wedding Hall'), ('MEETING', 'Meeting Room'), ('CONFERENCE', 'Conference Hall'), ('PARTY', 'Party Venue'), ('OUTDOOR_GARDEN', 'Outdoor Garden')], max_length=15, null=True)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hall_detail', to='properties.property')),
            ],
            options={
                'verbose_name': 'Hall Detail',
                'verbose_name_plural': 'Hall Details',
            },
        ),
        migrations.CreateModel(
            name='FavoriteProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_properties', to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='properties.property')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=properties.models.property_image_path)),
                ('is_primary', models.BooleanField(default=False)),
                ('caption', models.CharField(blank=True, default='', max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property')),
            ],
            options={
                'ordering': ['-is_primary', '-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('FAKE', 'Fake Listing'), ('DUPLICATE', 'Duplicate Listing'), ('INAPPROPRIATE', 'Inappropriate Content'), ('SCAM', 'Potential Scam'), ('OTHER', 'Other')], max_length=15)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('REVIEWED', 'Reviewed'), ('RESOLVED', 'Resolved')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='properties.property')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='properties.property')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['property_type', 'is_available'], name='properties__propert_5c46a0_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['price_monthly'], name='properties__price_m_680fe8_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['-created_at'], name='properties__created_9ef325_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='favoriteproperty',
            unique_together={('user', 'property')},
        ),
    ]
