# Generated by Django 5.1.4 on 2026-04-01 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='is_published',
            field=models.BooleanField(db_index=True, default=False, help_text='Set to True after the listing fee is paid.'),
        ),
    ]
