# Generated by Django 5.1.4 on 2026-04-01 09:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_property_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='maps_url',
            field=models.URLField(blank=True, default='', help_text='Google Maps / Apple Maps share link — renters open this instead of typing coordinates.', max_length=500),
        ),
        migrations.AddField(
            model_name='property',
            name='floor_number',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Floor (for apartment, condominium, real estate listings).', null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90)]),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180)]),
        ),
    ]
