# Generated by Django 5.1.4 on 2026-04-01 10:36

import django.core.validators
import properties.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_location_maps_url_property_floor_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyvideo',
            name='video',
            field=models.FileField(blank=True, help_text='Short walkthrough clip (MP4, WebM, MOV — max 75 MB on upload).', null=True, upload_to=properties.models.property_video_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'mov', 'mkv', 'm4v'])]),
        ),
        migrations.AlterField(
            model_name='propertyvideo',
            name='video_url',
            field=models.URLField(blank=True, default='', help_text='Optional: external link (e.g. YouTube) if not uploading a file.'),
        ),
    ]
