# Generated by Django 5.1.4 on 2026-04-01 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_propertyvideo_upload_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('APARTMENT', 'Apartment'), ('VILLA', 'Villa'), ('CONDOMINIUM', 'Condominium'), ('SERVICE_HOUSE', 'Service House'), ('REAL_ESTATE', 'Real Estate'), ('BUSINESS_SHOP', 'Business Shop'), ('HALL_RENTAL', 'Hall Rental')], db_index=True, max_length=15),
        ),
    ]
