# Generated by Django 5.1.4 on 2026-04-01 11:09

import django.core.validators
import properties.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_add_business_shop_property_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyvideo',
            name='video',
            field=models.FileField(blank=True, help_text='Short walkthrough clip (MP4, WebM, MOV — max 75 MB on upload).', null=True, upload_to=properties.models.property_video_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'mov', 'mkv', 'm4v', '3gp'])]),
        ),
    ]
