# Generated by Django 5.1.4 on 2026-04-01 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_propertyvideo_allow_3gp'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='shop_class_count',
            field=models.PositiveSmallIntegerField(blank=True, help_text='For business shops: number of classes (rooms, counters, or separate areas).', null=True),
        ),
    ]
