# Generated by Django 5.1.4 on 2026-04-06 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_property_shop_class_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='halldetail',
            name='capacity_min',
            field=models.PositiveIntegerField(blank=True, help_text='Minimum guests the hall is suited for (optional).', null=True),
        ),
    ]
