# Generated by Django 5.1.4 on 2026-04-19 12:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_property_listing_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('region', models.CharField(blank=True, default='', help_text='Regional state or charter (for grouping and search).', max_length=120)),
                ('search_text', models.TextField(blank=True, default='', help_text='Optional alternate spellings / transliterations (space-separated).')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=100, help_text='Lower values appear first in dropdowns.')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'cities',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.RemoveField(
            model_name='halldetail',
            name='capacity_min',
        ),
        migrations.AlterField(
            model_name='property',
            name='price_monthly',
            field=models.DecimalField(decimal_places=2, help_text='Monthly rent, short-term rate, or total asking price when listing is for sale.', max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='location',
            name='city_ref',
            field=models.ForeignKey(blank=True, help_text='Canonical city; keeps Location.city string in sync when set.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='properties.city'),
        ),
    ]
