# Generated by Django 5.1.4 on 2026-04-23 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_listing_packages'),
        ('properties', '0011_seed_ethiopian_cities'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='listing_slot_purchase',
            field=models.ForeignKey(blank=True, help_text='Purchase record that provided the slot for this published listing.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='payments.listingpackagepurchase'),
        ),
        migrations.AlterField(
            model_name='property',
            name='is_published',
            field=models.BooleanField(db_index=True, default=False, help_text='Set to True when published using a package slot (or legacy fee flow).'),
        ),
    ]
