"""
Canonical list of Ethiopian cities for seeding the City model.

name: Primary display name (Latin script, as used in filters and Location.city)
region: Administrative region or charter for search / grouping
sort_order: Lower = listed first (major cities first)
search_text: Extra tokens (alternate spellings) for API search
"""

ETHIOPIAN_CITIES_SEED = [
    {"name": "Addis Ababa", "region": "Addis Ababa", "sort_order": 1, "search_text": "finfine"},
    {"name": "Dire Dawa", "region": "Dire Dawa", "sort_order": 2, "search_text": ""},
    {"name": "Mekelle", "region": "Tigray", "sort_order": 3, "search_text": "mekele makelle"},
    {"name": "Gondar", "region": "Amhara", "sort_order": 4, "search_text": "gonder"},
    {"name": "Hawassa", "region": "Sidama", "sort_order": 5, "search_text": "awassa hawasa"},
    {"name": "Bahir Dar", "region": "Amhara", "sort_order": 6, "search_text": "bahirdar"},
    {"name": "Jimma", "region": "Oromia", "sort_order": 7, "search_text": "jima"},
    {"name": "Dessie", "region": "Amhara", "sort_order": 8, "search_text": "desse"},
    {"name": "Jijiga", "region": "Somali", "sort_order": 9, "search_text": "jigjiga"},
    {"name": "Shashamane", "region": "Oromia", "sort_order": 10, "search_text": "shashemene shashamene"},
    {"name": "Arba Minch", "region": "SNNPR", "sort_order": 11, "search_text": "arbaminch"},
    {"name": "Hosaena", "region": "Central Ethiopia", "sort_order": 12, "search_text": "hosaina hossana"},
    {"name": "Harar", "region": "Harari", "sort_order": 13, "search_text": "harer"},
    {"name": "Kombolcha", "region": "Amhara", "sort_order": 14, "search_text": ""},
    {"name": "Debre Berhan", "region": "Amhara", "sort_order": 15, "search_text": "debere berhan"},
    {"name": "Asella", "region": "Oromia", "sort_order": 16, "search_text": "asela"},
    {"name": "Adama", "region": "Oromia", "sort_order": 17, "search_text": "nazret nazareth"},
    {"name": "Nekemte", "region": "Oromia", "sort_order": 18, "search_text": "nekempte"},
    {"name": "Debre Markos", "region": "Amhara", "sort_order": 19, "search_text": "debre markos"},
    {"name": "Wolaita Sodo", "region": "SNNPR", "sort_order": 20, "search_text": "welayta soddo"},
    {"name": "Sodo", "region": "SNNPR", "sort_order": 21, "search_text": "wolaita"},
    {"name": "Mizan Teferi", "region": "SNNPR", "sort_order": 22, "search_text": "mizan teferi"},
    {"name": "Gambela", "region": "Gambela", "sort_order": 23, "search_text": "gambella"},
    {"name": "Assosa", "region": "Benishangul-Gumuz", "sort_order": 24, "search_text": "assosa asosa"},
    {"name": "Semera", "region": "Afar", "sort_order": 25, "search_text": ""},
    {"name": "Bule Hora", "region": "Oromia", "sort_order": 26, "search_text": "bulehora"},
    {"name": "Boditi", "region": "SNNPR", "sort_order": 27, "search_text": ""},
    {"name": "Woldiya", "region": "Amhara", "sort_order": 28, "search_text": "dessie wollo"},
    {"name": "Debre Tabor", "region": "Amhara", "sort_order": 29, "search_text": ""},
    {"name": "Aksum", "region": "Tigray", "sort_order": 30, "search_text": "axum"},
    {"name": "Adigrat", "region": "Tigray", "sort_order": 31, "search_text": ""},
    {"name": "Bishoftu", "region": "Oromia", "sort_order": 32, "search_text": "debre zeit debrezeit"},
    {"name": "Sebeta", "region": "Oromia", "sort_order": 33, "search_text": ""},
    {"name": "Burayu", "region": "Oromia", "sort_order": 34, "search_text": ""},
    {"name": "Holeta", "region": "Oromia", "sort_order": 35, "search_text": ""},
    {"name": "Lalibela", "region": "Amhara", "sort_order": 36, "search_text": "lalibella"},
    {"name": "Robe", "region": "Oromia", "sort_order": 37, "search_text": "bale robe"},
    {"name": "Dilla", "region": "SNNPR", "sort_order": 38, "search_text": ""},
    {"name": "Yirgalem", "region": "Sidama", "sort_order": 39, "search_text": "yergalem"},
    {"name": "Welkite", "region": "Central Ethiopia", "sort_order": 40, "search_text": "wolkite"},
    {"name": "Butajira", "region": "Central Ethiopia", "sort_order": 41, "search_text": ""},
    {"name": "Ambo", "region": "Oromia", "sort_order": 42, "search_text": ""},
    {"name": "Negele Borana", "region": "Oromia", "sort_order": 43, "search_text": "negele"},
    {"name": "Moyale", "region": "Oromia", "sort_order": 44, "search_text": ""},
    {"name": "Mega", "region": "Oromia", "sort_order": 45, "search_text": ""},
    {"name": "Konso", "region": "SNNPR", "sort_order": 46, "search_text": ""},
    {"name": "Turmi", "region": "SNNPR", "sort_order": 47, "search_text": "hamer"},
    {"name": "Gode", "region": "Somali", "sort_order": 48, "search_text": ""},
    {"name": "Kelafo", "region": "Somali", "sort_order": 49, "search_text": ""},
    {"name": "Dembi Dollo", "region": "Oromia", "sort_order": 50, "search_text": "dembi dolo"},
    {"name": "Bedele", "region": "Oromia", "sort_order": 51, "search_text": ""},
    {"name": "Chiro", "region": "Oromia", "sort_order": 52, "search_text": "asebe teferi"},
    {"name": "Fiche", "region": "Oromia", "sort_order": 53, "search_text": ""},
    {"name": "Gimbi", "region": "Oromia", "sort_order": 54, "search_text": ""},
    {"name": "Humera", "region": "Tigray", "sort_order": 55, "search_text": "humera"},
    {"name": "Injibara", "region": "Amhara", "sort_order": 56, "search_text": ""},
    {"name": "Jinka", "region": "SNNPR", "sort_order": 57, "search_text": ""},
    {"name": "Kebri Dehar", "region": "Somali", "sort_order": 58, "search_text": "kebri dehar"},
    {"name": "Korem", "region": "Tigray", "sort_order": 59, "search_text": ""},
]
