# Generated by Django 5.1.4 on 2026-05-07 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='review_type',
            field=models.CharField(choices=[('PROPERTY_REVIEW', 'Property Review'), ('LANDLORD_REVIEW', 'Property Owner Review'), ('TENANT_REVIEW', 'Tenant Review')], db_index=True, max_length=20),
        ),
    ]
