# Generated by Django 5.1.4 on 2026-04-01 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('LISTING_FEE', 'Listing Fee'), ('FEATURED_LISTING', 'Featured Listing'), ('VERIFICATION_FEE', 'Verification Fee'), ('SUBSCRIPTION', 'Subscription'), ('HALL_BOOKING', 'Hall Booking'), ('COMMISSION', 'Commission')], max_length=20),
        ),
    ]
