# Generated by Django 5.1.4 on 2026-04-23 19:00

import django.core.validators
import django.db.models.deletion
from decimal import Decimal

from django.conf import settings
from django.db import migrations, models


def seed_listing_packages(apps, schema_editor):
    ListingPackage = apps.get_model("payments", "ListingPackage")
    if ListingPackage.objects.exists():
        return
    rows = [
        dict(
            code="starter",
            name="Starter",
            listing_quota=1,
            price=Decimal("199.00"),
            compare_at_price=Decimal("199.00"),
            tagline="List one property",
            badge_label="",
            sort_order=10,
        ),
        dict(
            code="plus",
            name="Plus",
            listing_quota=5,
            price=Decimal("799.00"),
            compare_at_price=Decimal("995.00"),
            tagline="~20% vs 5 single listings",
            badge_label="Popular",
            sort_order=20,
        ),
        dict(
            code="pro",
            name="Pro",
            listing_quota=20,
            price=Decimal("2400.00"),
            compare_at_price=Decimal("3980.00"),
            tagline="~40% savings vs singles",
            badge_label="Best value",
            sort_order=30,
        ),
        dict(
            code="business",
            name="Business",
            listing_quota=50,
            price=Decimal("5000.00"),
            compare_at_price=Decimal("9950.00"),
            tagline="For agencies & teams",
            badge_label="",
            sort_order=40,
        ),
        dict(
            code="enterprise",
            name="Enterprise",
            listing_quota=100,
            price=Decimal("8000.00"),
            compare_at_price=Decimal("19900.00"),
            tagline="Lowest per-listing cost",
            badge_label="Lowest / listing",
            sort_order=50,
        ),
    ]
    for r in rows:
        ListingPackage.objects.create(**r)


def unseed_listing_packages(apps, schema_editor):
    ListingPackage = apps.get_model("payments", "ListingPackage")
    ListingPackage.objects.filter(
        code__in=["starter", "plus", "pro", "business", "enterprise"]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payment_payment_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('listing_quota', models.PositiveIntegerField(help_text='Number of concurrent listings this purchase can publish.')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='ETB', max_length=3)),
                ('validity_days', models.PositiveIntegerField(default=365, help_text='How long remaining slots are valid after purchase is paid.')),
                ('compare_at_price', models.DecimalField(blank=True, decimal_places=2, help_text='Anchor price for UI (e.g. 1×199 × quota).', max_digits=12, null=True)),
                ('tagline', models.CharField(blank=True, default='', max_length=200)),
                ('badge_label', models.CharField(blank=True, default='', help_text='e.g. "Best value"', max_length=50)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'listing package',
                'verbose_name_plural': 'listing packages',
                'ordering': ['sort_order', 'listing_quota'],
            },
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('LISTING_FEE', 'Listing Fee'), ('LISTING_PACKAGE', 'Listing package (slot bundle)'), ('FEATURED_LISTING', 'Featured Listing'), ('VERIFICATION_FEE', 'Verification Fee'), ('SUBSCRIPTION', 'Subscription'), ('HALL_BOOKING', 'Hall Booking'), ('COMMISSION', 'Commission')], max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='listing_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='payments.listingpackage'),
        ),
        migrations.CreateModel(
            name='ListingPackagePurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending payment'), ('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=10)),
                ('slots_total', models.PositiveIntegerField()),
                ('slots_used', models.PositiveIntegerField(default=0)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='payments.listingpackage')),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listing_package_purchase', to='payments.payment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_package_purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='payments_li_user_id_03a63a_idx')],
            },
        ),
        migrations.RunPython(seed_listing_packages, unseed_listing_packages),
    ]
