# Generated by Django 5.1

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0003_listing_packages"),
    ]

    operations = [
        migrations.AddField(
            model_name="listingpackagepurchase",
            name="low_balance_notified",
            field=models.BooleanField(
                default=False,
                help_text="Set when we sent 'one listing credit left' for this purchase.",
            ),
        ),
        migrations.AddField(
            model_name="listingpackagepurchase",
            name="expiry_warning_notified",
            field=models.BooleanField(
                default=False,
                help_text="Set when we sent a package expiring soon notification.",
            ),
        ),
    ]
