# Generated by GPT-5.2 on 2026-05-08

from django.db import migrations
from django.utils import timezone


def expire_duplicate_active_purchases(apps, schema_editor):
    ListingPackagePurchase = apps.get_model("payments", "ListingPackagePurchase")
    now = timezone.now()
    # For each user, keep the most recent ACTIVE purchase and expire the rest.
    user_ids = (
        ListingPackagePurchase.objects.filter(status="ACTIVE")
        .values_list("user_id", flat=True)
        .distinct()
    )
    for user_id in user_ids:
        actives = list(
            ListingPackagePurchase.objects.filter(user_id=user_id, status="ACTIVE")
            .order_by("-created_at")
            .values_list("id", flat=True)
        )
        if len(actives) <= 1:
            continue
        keep_id = actives[0]
        ListingPackagePurchase.objects.filter(
            user_id=user_id, status="ACTIVE"
        ).exclude(id=keep_id).update(status="EXPIRED", expires_at=now, updated_at=now)


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0004_listingpackagepurchase_notify_flags"),
    ]

    operations = [
        migrations.RunPython(expire_duplicate_active_purchases, migrations.RunPython.noop),
        migrations.RunSQL(
            sql=(
                "CREATE UNIQUE INDEX IF NOT EXISTS "
                "payments_lpp_unique_active_per_user "
                "ON payments_listingpackagepurchase(user_id) "
                "WHERE status = 'ACTIVE';"
            ),
            reverse_sql="DROP INDEX IF EXISTS payments_lpp_unique_active_per_user;",
        ),
    ]

